[wip] Preparing all the documents for our final submission.
opcushing/cs225-final-project-wikiracer pull request #22
Opened 2022-12-07 04:17 UTC by opcushing

This includes:
- `README.md` describes the layout of the project, where important files are, etc. Also includes installation instructions. 
- `team_contract.md` is the team contract we signed at the beginning of the semester.
- `results.md` should describe our results / findings from working on this project.
- `project_proposal.md` is what `README.md` used to be: the project proposal.

2022-12-11 22:35 UTC, opcushing reviewed
Looks good. I think this is ready for submission

2022-12-11 22:37 UTC, jamieRollison requested changes
good job me :) left and inline comment

2022-12-11 22:37 UTC, jamieRollison commented on README.md
> +- The final project presentation can be found [here](https://example.com)
correct this link when the video is posted

2022-12-12 02:04 UTC, jamieRollison approved these changes
merging this myself

2022-12-12 02:04 UTC, merged